//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.CommunityToolkit.Sample.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.CommunityToolkit.Sample.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string BoolToObjectConverterShortDescription {
            get {
                return ResourceManager.GetString("BoolToObjectConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string BoolToObjectConverterLongDescription {
            get {
                return ResourceManager.GetString("BoolToObjectConverterLongDescription", resourceCulture);
            }
        }
        
        internal static string DoubleToIntConverterShortDescription {
            get {
                return ResourceManager.GetString("DoubleToIntConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string DoubleToIntConverterLongDescription {
            get {
                return ResourceManager.GetString("DoubleToIntConverterLongDescription", resourceCulture);
            }
        }
        
        internal static string TextEntryPromt {
            get {
                return ResourceManager.GetString("TextEntryPromt", resourceCulture);
            }
        }
        
        internal static string EqualConverterShortDescription {
            get {
                return ResourceManager.GetString("EqualConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string EqualConverterLongDescription {
            get {
                return ResourceManager.GetString("EqualConverterLongDescription", resourceCulture);
            }
        }
        
        internal static string EqualPromtText {
            get {
                return ResourceManager.GetString("EqualPromtText", resourceCulture);
            }
        }
        
        internal static string IndexToArrayItemConverterShortDescription {
            get {
                return ResourceManager.GetString("IndexToArrayItemConverterShortDescription", resourceCulture);
            }
        }
        
        internal static string IndexToArrayItemConverterLongDescription {
            get {
                return ResourceManager.GetString("IndexToArrayItemConverterLongDescription", resourceCulture);
            }
        }
    }
}
